theme: jekyll-theme-primer
title: CS109a - Group 10 Final Project
description: CS109a - Group 10 Final Project
baseurl:
repository: jamesm-vt/cs109a_adni
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
